### ISSUE TITLE
Live patches rely on in-disk images of libraries

### ISSUE THREAD

**Issue by inconstante** [SUSE/libpulp#20]
Currently, libpulp.so needs to open the in-disk image of target libraries and of libpulp.so itself to learn about:

  1. the address of dlsym, which gets interposed;
  1. the addresses of to-be-patched functions;
  1. the addresses of live-patch support functions, e.g. `__ulp_trigger`;
  1. ~the load bias~.

However, requiring the disk-image has a problem... Since the in-disk image of the library and the in-memory image loaded by the target process must be identical, it makes it impossible for target libraries, as well as libpulp.so, to be updated in-disk, which would only work if package updates were forbidden and that is unreasonable.

Recently, #19 added a mechanism where addresses (more specifically offsets) get recorded in the metadata file, so that relying on in-disk images is not necessary. On the other hand, #19 only deals with addresses of LOCAL variables.

This Issue is here to remind us that we need to stop relying on in-disk images and that extending the metadata file (like in #19) is probably a good option.

**Comment by giulianobelinassi** [comment]
Well, if you look carefully:

1. This only happens when the process starts. This means that the library is present there, else the pachaable program wouldn't have launched at all with a missing library error.

2. Actually, we find that using `dlsym`.

3. It actually may be the only existing problem here.

**Comment by giulianobelinassi** [comment]
Isn't this fixed in commit `76beed4595eabc1d80d8fe68bc44e7cf25501dbb` ?

**Comment by susematz** [comment]
Not yet.  tools/introspection.c also contains code parsing ELF files from disk in order to know the addresses of the target process' libpulp function.  (See get_loaded_symbol_addr).  That process already uses in-memory reading for most of what it needs (e.g. linkmap base from the target) just for the symbol lookup it opens the file and uses libelf.

So, that would need changing as well.  (And now it's clear why I somewhere mumbled about symbol reading from a remote process, but then managed to think that that was overthinking :-) ).

**Comment by giulianobelinassi** [comment]
Done in `5982650d2608f3600efd303c8071a4d7ee3065ff`
