### ISSUE TITLE
Reduce the size of the nop padding area in function prologues

### ISSUE THREAD

**Issue by inconstante** [SUSE/libpulp#33]
If pull request #32 gets approved and merged, the size of the nop padding area could be shrunk.

Rationale:

Before pull request #32, the function prologue looks like this:

```
    function prologue:
  ┌───> push    %rdi
  │     movq    $index, %rdi
  │     jmp     0x0(%rip)
  │     <data>  <function version selection routine>
  │ function entry:
  └──── jmp     <function prologue>
```

After, it becomes:

```
    function prologue:
        push    %rdi           <-- Unused!
        movq    $index, %rdi   <-- Unused!
  ┌───> jmp     0x0(%rip)
  │     <data>  <target function>
  │ function entry:
  └──── jmp     <follow arrow :)>
```

I.e. the first two instructions become useless, so the nop padding area can be shorter.

**Comment by susematz** [comment]
Hmm, I'm split minds here.  Obviously it's bad to reserve space for stuff we don't need.  OTOH, if we ever change our way of how the control is transferred to new function versions (e.g. by re-implementing frame stealing, or some other fantastic consistency model) it might help if the target libraries already have comfortable space in the preamble, instead of them being
recompiled to provide that additional space agan.

OTOOH this all could still work without recompilation if the <target function> would be a (function-specific) block of wrapper code (space provided by mmap from libpulp) that provides the additional instructions needed for the hypothetical other consistency model.  So it could be made to work also when space is removed.

(With the new code sequence we loose the method of "identifying" the patched function (what was $index before), because
there's no need for that right now.)

I think, for now, make the nop padding area smaller.

**Comment by giulianobelinassi** [comment]
Done in `92688fe4e581f1684410951fd075a2578a7e3532`
